### ISSUE TITLE
[Feature-Request] Timeline images

### ISSUE THREAD

**Issue by valoricDe** [Itzhep/youtube#1]
Hi, 
I would love to create a browser extension which shows in customizable speeds all the pregenerated images which are shown in the timeline of a video (5s steps).

Do you have a hint how to do that?
Would you be open to have this feature integrated in this project?

This is the URL structure of one image:
https://i.ytimg.com/sb/FlO4edY7b5s/storyboard3_L3/M18.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgi12K-3Bg==&sigh=rs%24AOn4CLCI3dd2SRoGDYqy-y51LSXsmMOTBA

where you can iterate from M0 to Mxx.
Question is how to get the sqp and sigh query param

**Comment by Itzhep** [comment]
Hi,

Creating a browser extension to display pregenerated images from YouTube's video timeline at customizable speeds sounds like a great idea!

To achieve this, follow these steps:

Extracting Storyboard Data:

YouTube stores storyboard images in a specific format, but the sqp and sigh parameters are unique to each video. You can find these parameters in the video’s metadata.
Use browser developer tools to inspect network requests when loading a video. Look for requests to player_response or similar, which may include the storyboard data with these parameters.
Generating URLs:

The base URL for storyboard images is consistent, but the sqp and sigh parameters need to be obtained dynamically. You will need to parse these from the video metadata response.
Building the Extension:

Create a browser extension that injects JavaScript into YouTube video pages to extract the storyboard information.
Implement a UI for the extension that allows users to set the speed for displaying images (e.g., 5-second intervals).
Use JavaScript to cycle through the storyboard images according to the user’s speed setting.
If you’re interested in integrating this feature into your existing project, I'd be glad to discuss how we can incorporate it and make it fit seamlessly with your current setup.

**Comment by valoricDe** [comment]
Lol, beat me with AI xD
I hope the sqp and sigh parameters are really in the video metadata. I will have a look ;)

**Comment by Itzhep** [comment]
hi , sorry thats my new project (auto issues answer) i do not to much about your idea but mybe in the feature i make it
